artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/harshmdev/projects/raw/main/squad.zip
  local_data_file: artifacts/data_ingestion/squad.zip
  unzip_dir: artifacts/data_ingestion