artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/harshmdev/projects/raw/main/squad.zip
  local_data_file: artifacts/data_ingestion/squad.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","validation"]

data_transformation:
  root_dir: artifacts/data_preparation
  data_path: artifacts/data_ingestion/squad

